
package desktopApp.view;

import desktopApp.controller.DepartmentClient;
import desktopApp.controller.DeptManagerClient;
import desktopApp.controller.EmployeeClient;
import desktopApp.model.Department;
import desktopApp.model.DeptManager;
import desktopApp.model.Employee;
import desktopApp.model.Model;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Home extends javax.swing.JFrame {
        
    private final EmployeeClient ec;
    private final DepartmentClient dc;
    private final DeptManagerClient dmc;    
    private final DefaultTableModel tableModel;
    
    public Home(EmployeeClient ec, DepartmentClient dc, DeptManagerClient dmc) {
        this.ec = ec;
        this.dc = dc;
        this.dmc = dmc;
        
        initComponents();
        tableModel = (DefaultTableModel) table.getModel();
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnReadAll = new javax.swing.JButton();
        btnReadByID = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        scrollTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        scrollList = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnReadAll.setText("Leer todos");
        btnReadAll.setMinimumSize(new java.awt.Dimension(100, 30));
        btnReadAll.setPreferredSize(new java.awt.Dimension(100, 30));
        btnReadAll.addActionListener(this::btnReadAllActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btnReadAll, gridBagConstraints);

        btnReadByID.setText("Leer por ID");
        btnReadByID.setMinimumSize(new java.awt.Dimension(100, 30));
        btnReadByID.setPreferredSize(new java.awt.Dimension(100, 30));
        btnReadByID.addActionListener(this::btnReadByIDActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btnReadByID, gridBagConstraints);

        txtID.setMinimumSize(new java.awt.Dimension(100, 30));
        txtID.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(txtID, gridBagConstraints);

        scrollTable.setMinimumSize(new java.awt.Dimension(700, 400));
        scrollTable.setPreferredSize(new java.awt.Dimension(700, 400));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setMinimumSize(new java.awt.Dimension(700, 1000));
        table.setPreferredSize(new java.awt.Dimension(700, 1000));
        scrollTable.setViewportView(table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(scrollTable, gridBagConstraints);

        btnUpdate.setText("Actualizar");
        btnUpdate.setMinimumSize(new java.awt.Dimension(100, 30));
        btnUpdate.setPreferredSize(new java.awt.Dimension(100, 30));
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btnUpdate, gridBagConstraints);

        btnDelete.setText("Eliminar");
        btnDelete.setMinimumSize(new java.awt.Dimension(100, 30));
        btnDelete.setPreferredSize(new java.awt.Dimension(100, 30));
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btnDelete, gridBagConstraints);

        btnCreate.setText("Crear");
        btnCreate.setMinimumSize(new java.awt.Dimension(100, 30));
        btnCreate.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCreate.addActionListener(this::btnCreateActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(btnCreate, gridBagConstraints);

        scrollList.setMinimumSize(new java.awt.Dimension(100, 70));
        scrollList.setPreferredSize(new java.awt.Dimension(100, 70));

        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "employees", "departments", "dept managers" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.setMinimumSize(new java.awt.Dimension(100, 70));
        list.setPreferredSize(new java.awt.Dimension(100, 70));
        scrollList.setViewportView(list);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        jPanel1.add(scrollList, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadAllActionPerformed
        String tableDecision = getOptionByList();
        if (tableDecision == null) return;
        
        tableModel.setRowCount(0);
        tableModel.setRowCount(1);
        
        switch(tableDecision) {            
            case "employees":         
                setTableColumns(new String[]{"empNo", "birthDate", "firstName", "lastName", "gender", "hireDate"});                                
                setTableRows(ec.get());                
                break;
            case "departments":                                                                
                setTableColumns(new String[]{"dept_no", "dept_name"});                
                setTableRows(dc.get());                
                break;
            case "dept managers":                                                
                setTableColumns(new String[]{"emp_no", "first_name", "last_name", "dept_no", "dept_name", "from_date", "to_date"});
                setTableRows(dmc.get());                                                                
                break;            
        }
    }//GEN-LAST:event_btnReadAllActionPerformed

    private void btnReadByIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadByIDActionPerformed
        String tableDecision = getOptionByList();
        if (tableDecision == null) return;                
                
        tableModel.setRowCount(0);
        tableModel.setRowCount(1);
        
        String id = txtID.getText();
        
        switch(tableDecision) {            
            case "employees":         
                setTableColumns(new String[]{"empNo", "birthDate", "firstName", "lastName", "gender", "hireDate"});                                                                
                setTableRow(ec.getById(Integer.parseInt(id)));                
                break;
            case "departments":                                                                
                setTableColumns(new String[]{"dept_no", "dept_name"});                
                setTableRow(dc.getById(id));                
                break;
            case "dept managers":                                                
                setTableColumns(new String[]{"emp_no", "first_name", "last_name", "dept_no", "dept_name", "from_date", "to_date"});
                setTableRows(dmc.getByIdEmployeer(Integer.parseInt(id)));                
                break;            
        }
    }//GEN-LAST:event_btnReadByIDActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String tableDecision = getOptionByList();
        int selectedRow = table.getSelectedRow();
        if (tableDecision == null || selectedRow == -1) return;
                
        Object element = createObjectBySelectedRow(selectedRow, tableDecision);
        Object updatedElement = null; 
        
        switch(tableDecision) {            
            case "employees":                    
                updatedElement = ec.put((Employee) element);
                break;
            case "departments":                                                                
                updatedElement = dc.put((Department) element);                
                break;
            case "dept managers":                                                
                JOptionPane.showMessageDialog(null, "Tabla 'dept managers' no cuenta con funcionalidad 'Actualizar'");
                return;                           
        }
        
        if (updatedElement == null) return;//exist an error executing 'PUT' instruction
        
        updateTableRow(updatedElement, selectedRow, tableDecision);//we need to update the table
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String tableDecision = getOptionByList();
        int selectedRow = table.getSelectedRow();
        if (tableDecision == null || selectedRow == -1) return;
        
        switch(tableDecision) {
            case "employees": 
                int empNo = Integer.parseInt(tableModel.getValueAt(selectedRow, 0).toString());
                
                if (ec.delete(empNo))
                    tableModel.removeRow(selectedRow);
                break;
            case "departments":                                                                
                String deptNo = tableModel.getValueAt(selectedRow, 0).toString();
                
                if (dc.delete(deptNo)) 
                    tableModel.removeRow(selectedRow);
                break;
            case "dept managers":   
                empNo = Integer.parseInt(tableModel.getValueAt(selectedRow, 0).toString());
                deptNo = tableModel.getValueAt(selectedRow, 3).toString();
                
                if (dmc.delete(empNo, deptNo));
                    tableModel.removeRow(selectedRow);                    
                break;                
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String tableDecision = getOptionByList();
        int selectedRow = table.getSelectedRow();
        if (tableDecision == null || selectedRow != 0) return;
        
        Object element = createObjectBySelectedRow(selectedRow, tableDecision);        
        Object created = null;
        
        switch(tableDecision) {            
            case "employees":                    
                created = ec.post((Employee) element);                
                break;
            case "departments":                                                                
                created = dc.post((Department) element);
                break;
            case "dept managers":     
                created = dmc.post((DeptManager) element);
                break;                                
        }
        
        updateTableRow(created, selectedRow, tableDecision);
    }//GEN-LAST:event_btnCreateActionPerformed
    
    private String getOptionByList() {        
        return list.getSelectedValue();
    }  
    
    private void setTableColumns(String[] colums) {
        tableModel.setColumnIdentifiers(colums);
    }
    
    private void setTableRows(Object[] rows) {        
        if (rows == null) return;
        
        for (Object r : rows)                     
            tableModel.addRow(((Model) r).getData());                                        
    }
    
    private void setTableRow(Object row) {
        if (row == null) return;
        
        tableModel.addRow(((Model) row).getData());
    }
    
    private Object createObjectBySelectedRow(int selectedRow, String tableDecision) {
        switch(tableDecision) {
            case "employees":
                Object key = tableModel.getValueAt(selectedRow, 0);                
                int empNo;
                empNo = (key == null || key == "") ? 0 : Integer.parseInt(key.toString());
                String birthDate = getDate(tableModel.getValueAt(selectedRow, 1).toString());
                String firstName = tableModel.getValueAt(selectedRow, 2).toString();
                String lastName = tableModel.getValueAt(selectedRow, 3).toString();
                String gender = tableModel.getValueAt(selectedRow, 4).toString();
                String hireDate = getDate(tableModel.getValueAt(selectedRow, 5).toString());
                                
                return new Employee(empNo, birthDate, firstName, lastName, gender, hireDate);                                
            case "departments":                                                                                
                key = tableModel.getValueAt(selectedRow, 0);
                String deptNo = (key == null) ? "" : key.toString();
                String deptName = tableModel.getValueAt(selectedRow, 1).toString();
                
                return new Department(deptNo, deptName);                                        
            case "dept managers":
                deptNo = tableModel.getValueAt(selectedRow, 3).toString();
                empNo = Integer.parseInt(tableModel.getValueAt(selectedRow, 0).toString());
                String fromDate = tableModel.getValueAt(selectedRow, 5).toString();
                String toDate = tableModel.getValueAt(selectedRow, 6).toString();                 
                
                return new DeptManager(empNo, deptNo, fromDate, toDate);
        }                
        return null;
    }
    
    private String getDate(String completeDate) {
        return completeDate.substring(0, 10);
    }
    
    private void updateTableRow(Object updatedElement, int selectedRow, String tableDecision) {
        if (updatedElement == null) return;
        
        switch(tableDecision) {
            case "employees":
                Employee e = (Employee) updatedElement;
                tableModel.setValueAt(e.empNo, selectedRow, 0); 
                tableModel.setValueAt(e.birthDate, selectedRow, 1); 
                tableModel.setValueAt(e.firstName, selectedRow, 2); 
                tableModel.setValueAt(e.lastName, selectedRow, 3); 
                tableModel.setValueAt(e.gender, selectedRow, 4); 
                tableModel.setValueAt(e.hireDate, selectedRow, 5);                                         
                break;                
            case "departments":                                                                
                Department d = (Department) updatedElement;
                tableModel.setValueAt(d.deptNo, selectedRow, 0);                 
                tableModel.setValueAt(d.deptName, selectedRow, 1);                 
                break;                            
            case "dept managers":
                DeptManager dm = (DeptManager) updatedElement;
                Employee employeeOfDeptManager = ec.getById(dm.empNo);
                Department departmentOfDeptManager = dc.getById(dm.deptNo);
                
                tableModel.setValueAt(dm.empNo, selectedRow, 0);
                tableModel.setValueAt(employeeOfDeptManager.firstName, selectedRow, 1);                 
                tableModel.setValueAt(employeeOfDeptManager.lastName, selectedRow, 2);                 
                tableModel.setValueAt(dm.deptNo, selectedRow, 3);                 
                tableModel.setValueAt(departmentOfDeptManager.deptName, selectedRow, 4);                 
                tableModel.setValueAt(dm.fromDate, selectedRow, 5);                 
                tableModel.setValueAt(dm.toDate, selectedRow, 6);                         
                break;                
        }        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReadAll;
    private javax.swing.JButton btnReadByID;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JList<String> list;
    private javax.swing.JScrollPane scrollList;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
